title: Mar Anderson F. princer
logo: /assets/img/marlogo.jpg
email: princermar12@gmail.com
description: I write, paint, and calculate stuff. 
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

platforms:
  - name: Instagram
    icon: <i class="fa-brands fa-instagram"></i>
    link: https://instagram.com/marmafp
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/marprincer

navigation:
  - name: Home
    link: ./

  - name: Research
    link: ./

  - name: Blog
    link: ./

  - name: About
    link: ./

remote_theme: vaibhavvikas/jekyll-theme-minimalistic

      
  
